version: '3'

services:
  nginx:
    image: nginx:1.12-alpine
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./waterbot:/app:delegated
    labels:
      traefik.enable: 'true'
      traefik.frontend.rule: 'Host:${DOMAIN}'
    networks:
      - default
      - web
    depends_on:
      - bot
    restart: ${RESTART}

  bot:
    build:
      context: docker/php
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      PHP_USER_ID: 1000
    restart: ${RESTART}

  php-cron:
    build:
      context: docker/php
      args:
        PHP_BASE_IMAGE_VERSION: 7.2-fpm
    environment:
      PHP_USER_ID: 1000
    volumes:
      - ./docker/php-cron/docker-php-entrypoint:/usr/local/bin/docker-php-entrypoint:delegated
      - ./docker/php-cron/schedule:/etc/cron.d/schedule
      - ./:/app:delegated
    command: cron -f
    restart: ${RESTART}

networks:
  web:
    external: true
